#!/usr/bin/env python3
"""playground.py — the index of every playground piece, and each piece's version strip.

    python3 brain/playground.py [--open]

`brain/playground/<slug>/` holds a piece: `piece.md` (the record) and `vNN-<name>.html` (the
versions, every one kept). This reads the folders and writes two projections:

  brain/playground/index.html          every piece, its status, its versions, plus the
                                       exploration spreads — one page to open first
  brain/playground/<slug>/versions.js  `window.PLAYGROUND` for that piece, which is what gives
                                       each version file its version strip in the bar

Both are regenerated from the files and never read back. Delete them and nothing is lost.
`render.py` runs this with the other projections; `/playground` runs it alone after writing a
version, so the strip knows about the file that was just made.

The record format is `brain/playground/README.md`. This parses the little it needs: the
frontmatter's `project:` and `status:`, the title line, `Brief:`, `Final:`, `Shipped:`, and the
`## Versions` list, matched to files by their `vNN` prefix.
"""

from __future__ import annotations

import argparse
import html
import json
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path

BRAIN = Path(__file__).resolve().parent
ROOT = BRAIN.parent
DIR = BRAIN / "playground"
RESERVED = {"_canvas", "_template"}
STATUSES = ("exploring", "current", "final", "shipped")
VERSION_FILE = re.compile(r"^(v\d{2,})(?:-([a-z0-9][a-z0-9-]*))?\.html$")

sys.path.insert(0, str(BRAIN))
from config import PROJECT_NAME, MULTI_PROJECT, PROJECT_LABEL  # noqa: E402
from feed import CSS, FONT_LINK  # noqa: E402


def frontmatter(text: str) -> dict:
    m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    out = {}
    if not m:
        return out
    for line in m.group(1).splitlines():
        if ":" in line:
            k, v = line.split(":", 1)
            out[k.strip()] = v.split("#", 1)[0].strip()
    return out


def field(text: str, name: str) -> str:
    m = re.search(rf"^{name}:\s*(.+?)\s*$", text, re.M)
    v = m.group(1) if m else ""
    return "" if v.startswith("{{") else v


def parse(folder: Path) -> dict:
    """One piece: the record plus the files that exist beside it."""
    rec = folder / "piece.md"
    text = rec.read_text(encoding="utf-8") if rec.exists() else ""
    fm = frontmatter(text)
    title_m = re.search(r"^# (.+)$", text, re.M)
    notes = {}
    for m in re.finditer(r"^- (v\d{2,})\s*—\s*(\S+)?\s*—?\s*(.*)$", text, re.M):
        notes[m.group(1)] = (m.group(2) or "", m.group(3).strip())
    versions = []
    for f in sorted(folder.glob("*.html")):
        vm = VERSION_FILE.match(f.name)
        if vm:
            date, note = notes.get(vm.group(1), ("", ""))
            versions.append({"file": f.name, "v": vm.group(1),
                             "label": vm.group(1) + (" · " + vm.group(2).replace("-", " ") if vm.group(2) else ""),
                             "date": date, "note": note})
    shipped = sorted(f.name for f in folder.glob("shipped*.html"))
    final = field(text, "Final")
    final_file = next((v["file"] for v in versions if v["v"] == final or v["file"] == final), "")
    return {
        "slug": folder.name, "path": rec, "has_record": rec.exists(),
        "title": title_m.group(1).strip() if title_m else folder.name,
        "project": fm.get("project", ""), "status": fm.get("status", "") or "exploring",
        "source": fm.get("source", ""), "brief": field(text, "Brief"),
        "exploration": field(text, "Exploration"), "decision": field(text, "Decision"),
        "final": final, "final_file": final_file, "shipped_note": field(text, "Shipped"),
        "versions": versions, "shipped": shipped,
        "unlogged": [v["v"] for v in versions if v["v"] not in notes],
    }


def pieces() -> list[dict]:
    if not DIR.exists():
        return []
    return [parse(p) for p in sorted(DIR.iterdir())
            if p.is_dir() and p.name not in RESERVED and not p.name.startswith(".")]


def versions_js(p: dict) -> str:
    data = {"slug": p["slug"], "title": p["title"], "status": p["status"],
            "versions": p["versions"] + [{"file": s, "v": "shipped", "label": "shipped", "date": "", "note": ""} for s in p["shipped"]],
            "final": p["final_file"]}
    return ("// generated by brain/playground.py from piece.md and the files beside it — do not edit\n"
            f"window.PLAYGROUND = {json.dumps(data, ensure_ascii=False)};\n")


PAGE_CSS = """
.wrap{max-width:980px}
.piece{display:grid;grid-template-columns:1fr 2fr;gap:12px 40px;padding:26px 0;border-top:1px solid var(--rule)}
.piece h3{margin:0 0 4px;font-size:20px}
.piece .brief{font-size:15px;color:var(--ink-2);margin:0 0 8px;max-width:48ch}
.piece .facts{font-size:12px;color:var(--ink-3);display:flex;flex-wrap:wrap;gap:4px 14px}
.piece .facts a{color:var(--blue);text-decoration:none}
.status{font-size:10.5px;font-weight:600;letter-spacing:.11em;text-transform:uppercase;margin-bottom:10px;color:var(--ink-3)}
.status[data-s="final"]{color:var(--ink)}.status[data-s="shipped"]{color:var(--green)}
.status[data-s="current"]{color:var(--ochre)}
.versions{list-style:none;margin:0;padding:0;font-size:14px}
.versions li{display:grid;grid-template-columns:150px 92px 1fr;gap:16px;padding:7px 0;border-bottom:1px solid var(--rule-soft);align-items:baseline}
.versions li:last-child{border-bottom:0}
.versions a{color:var(--ink);text-decoration:none;font-weight:500;font-variant-numeric:tabular-nums}
.versions a:hover{text-decoration:underline}
.versions .date{color:var(--ink-3);font-size:13px;font-variant-numeric:tabular-nums}
.versions .note{color:var(--ink-2);font-size:14px;line-height:1.5}
.versions li.final a::after{content:"final";margin-left:8px;font-size:10px;font-weight:600;letter-spacing:.1em;text-transform:uppercase;color:var(--ink-3)}
.versions li.shipped a{color:var(--green)}
.empty{color:var(--ink-3);font-size:15px}
.spreads{list-style:none;margin:0;padding:0;font-size:15px}
.spreads li{padding:8px 0;border-bottom:1px solid var(--rule-soft)}
.spreads a{color:var(--ink);text-decoration:none}.spreads a:hover{text-decoration:underline}
.spreads .date{color:var(--ink-3);font-size:13px;margin-right:12px;font-variant-numeric:tabular-nums}
.warn{color:var(--ochre)}
"""


def piece_html(p: dict) -> str:
    facts = []
    if MULTI_PROJECT and p["project"]:
        facts.append(html.escape(PROJECT_LABEL.get(p["project"], p["project"])))
    if p["source"]:
        facts.append("from " + html.escape(p["source"]))
    if p["exploration"]:
        facts.append("exploration " + html.escape(p["exploration"]))
    if p["decision"]:
        facts.append("decision " + html.escape(p["decision"]))
    if p["shipped_note"]:
        facts.append("shipped " + html.escape(p["shipped_note"]))
    if not p["has_record"]:
        facts.append('<span class="warn">no piece.md</span>')
    if p["unlogged"]:
        facts.append(f'<span class="warn">{", ".join(p["unlogged"])} not in the version log</span>')
    rows = []
    for v in reversed(p["versions"]):
        cls = " final" if v["file"] == p["final_file"] else ""
        rows.append(f'<li class="{cls.strip()}"><a href="{p["slug"]}/{v["file"]}">{html.escape(v["label"])}</a>'
                    f'<span class="date">{html.escape(v["date"])}</span>'
                    f'<span class="note">{html.escape(v["note"])}</span></li>')
    for s in p["shipped"]:
        rows.append(f'<li class="shipped"><a href="{p["slug"]}/{s}">{html.escape(s[:-5])}</a>'
                    f'<span class="date"></span><span class="note">the HTML counterpart of what went live</span></li>')
    versions = f'<ul class="versions">{"".join(rows)}</ul>' if rows else '<p class="empty">no versions yet</p>'
    return f"""<div class="piece" id="{html.escape(p["slug"])}">
  <div>
    <div class="status" data-s="{html.escape(p["status"])}">{html.escape(p["status"])}</div>
    <h3>{html.escape(p["title"])}</h3>
    {f'<p class="brief">{html.escape(p["brief"])}</p>' if p["brief"] else ""}
    <div class="facts">{" · ".join(facts)}</div>
  </div>
  {versions}
</div>"""


def spreads_html() -> str:
    pages = sorted((BRAIN / "explorations").glob("*.html"), reverse=True)
    if not pages:
        return ""
    items = []
    for pg in pages:
        m = re.match(r"(\d{4}-\d{2}-\d{2})-(.+)", pg.stem)
        date, name = (m.group(1), m.group(2).replace("-", " ")) if m else ("", pg.stem)
        items.append(f'<li><span class="date">{date}</span><a href="../explorations/{pg.name}">{html.escape(name)}</a></li>')
    return (f'<div class="panel"><div class="kicker">Explorations · the spreads, one click away</div>'
            f'<ul class="spreads">{"".join(items)}</ul></div>')


def build(ps: list[dict]) -> str:
    stamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    if MULTI_PROJECT:
        groups: dict = {}
        for p in ps:
            groups.setdefault(p["project"] or "—", []).append(p)
        body = "".join(
            f'<div class="panel"><div class="kicker">{html.escape(PROJECT_LABEL.get(k, k))}</div>'
            + "".join(piece_html(p) for p in v) + "</div>" for k, v in groups.items())
    else:
        body = "".join(piece_html(p) for p in ps)
    if not ps:
        body = ('<p class="empty">No pieces yet. <code>/playground</code> starts one from a design or '
                'from nothing; <code>/prototype</code> builds a first pass here.</p>')
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Playground — {html.escape(PROJECT_NAME)}</title>
{FONT_LINK}<style>{CSS}{PAGE_CSS}</style></head><body>
<div class="wrap">
<div class="top">
  <div class="kicker">{html.escape(PROJECT_NAME)} · playground</div>
  <h1>Every piece, every version, nothing lost.</h1>
  <div class="meta">generated {stamp} from <code>brain/playground/*/piece.md</code> and the files
    beside them — regenerate with <code>python3 brain/playground.py</code></div>
</div>
{body}
{spreads_html()}
</div></body></html>"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--open", action="store_true")
    args = ap.parse_args()
    if not DIR.exists():
        print("no brain/playground/ — nothing to render")
        return 0
    ps = pieces()
    for p in ps:
        (DIR / p["slug"] / "versions.js").write_text(versions_js(p), encoding="utf-8")
    out = DIR / "index.html"
    out.write_text(build(ps), encoding="utf-8")
    n = sum(len(p["versions"]) for p in ps)
    print(f"{out.relative_to(ROOT)}  ·  {len(ps)} piece(s), {n} version(s)")
    for p in ps:
        flags = []
        if not p["has_record"]:
            flags.append("no piece.md")
        if p["unlogged"]:
            flags.append(f"{', '.join(p['unlogged'])} not in the version log")
        if flags:
            print(f"  {p['slug']}: " + "; ".join(flags))
    if args.open:
        subprocess.run(["open", str(out)], check=False)
    return 0


if __name__ == "__main__":
    sys.exit(main())
